/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurant_billing;
import java.sql.*;
import javax.swing.*;


/**
 *
 * @author ram arora
 */
public class Add_Dish extends javax.swing.JInternalFrame implements globalvariables {

    /**
     * Creates new form Add_Dish
     */
    public Add_Dish() {
        initComponents();
        
        
        {
         Connection myconnection;
            try
            {
            myconnection=DriverManager.getConnection(PATH+PLACE,USERNAME,PASSWORD);
            try
            {
            String a="select * from mealtable";
            PreparedStatement mystatement=myconnection.prepareStatement(a); 
            ResultSet myresult=mystatement.executeQuery();
            if(myresult.next())
            {
            do
            
            {
            mealbox.addItem(myresult.getString("meal"));
            }
            while(myresult.next());
            }
            else
            {
            JOptionPane.showMessageDialog(rootPane, "No Meals Added yet");
            }
            }
            catch(Exception e)
            {
            JOptionPane.showMessageDialog(rootPane, "Error in query " + e.getMessage());
            }
            finally
            {
            myconnection.close();
            }

            }
            catch(Exception e)
            {
            JOptionPane.showMessageDialog(rootPane, "Error in Connection " + e.getMessage());
            }
        }
            
        {    
             Connection myconnection2;
            try
            {
            myconnection2=DriverManager.getConnection(PATH+PLACE,USERNAME,PASSWORD);
            try
            {
            String a2="select * from mealtypetable";
            
            PreparedStatement mystatement2=myconnection2.prepareStatement(a2); 
            
            ResultSet myresult2=mystatement2.executeQuery();
            if(myresult2.next())
            {
            do
            {
            mealtypebox.addItem(myresult2.getString("mealtype"));
            }
            while(myresult2.next());
            }
            else
            {
            JOptionPane.showMessageDialog(rootPane, "No Mealtypes Added yet");
            }
            }
            catch(Exception e)
            {
            JOptionPane.showMessageDialog(rootPane, "Error in query " + e.getMessage());
            }
            finally
            {
            myconnection2.close();
            }

            }
            catch(Exception e)
            {
            JOptionPane.showMessageDialog(rootPane, "Error in Connection " + e.getMessage());
            }
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        mealbox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        dishbox = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mealtypebox = new javax.swing.JComboBox<>();
        pricebox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Add Dish");

        jButton1.setText("Add Dish");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        mealbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Meal" }));
        mealbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mealboxActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("MealType:");

        dishbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dishboxActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Meal:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Dish:");

        mealtypebox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Mealtype" }));
        mealtypebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mealtypeboxActionPerformed(evt);
            }
        });

        pricebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceboxActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Price:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(mealtypebox, 0, 165, Short.MAX_VALUE)
                                .addComponent(mealbox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dishbox)
                                .addComponent(pricebox)))
                        .addGap(0, 30, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(mealbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(mealtypebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dishbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(pricebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try
        {
            Connection myconnection=DriverManager.getConnection(PATH+PLACE,USERNAME,PASSWORD);
            try
            {
                String a="insert into dishtable(meal,mealtype,dish,price) values(?,?,?,?)";
                PreparedStatement mystatement=myconnection.prepareStatement(a);
                mystatement.setString(1,mealbox.getSelectedItem().toString());
                mystatement.setString(2,mealtypebox.getSelectedItem().toString());
                mystatement.setString(3,dishbox.getText());
                mystatement.setString(4,pricebox.getText());

                if(mystatement.executeUpdate()==1)
                {
                    JOptionPane.showMessageDialog(rootPane,"Dish Added Successfully");

                }
                else {
                    JOptionPane.showMessageDialog(rootPane,"Dish Not Added.");
                }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane,"Error in Query"+e.getMessage());
            }
            finally
            {
                myconnection.close();
            }

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane,"Error in Connection"+e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void mealboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mealboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mealboxActionPerformed

    private void dishboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dishboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dishboxActionPerformed

    private void mealtypeboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mealtypeboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mealtypeboxActionPerformed

    private void priceboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceboxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dishbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<String> mealbox;
    private javax.swing.JComboBox<String> mealtypebox;
    private javax.swing.JTextField pricebox;
    // End of variables declaration//GEN-END:variables
}
