/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurant_billing;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import static restaurant_billing.globalvariables.PASSWORD;
import static restaurant_billing.globalvariables.PATH;
import static restaurant_billing.globalvariables.PLACE;
import static restaurant_billing.globalvariables.USERNAME;

/**
 *
 * @author ram arora
 */
public class Vacate_Tables__Recieve_Payment extends javax.swing.JInternalFrame {

    
    public static int a;
    public Vacate_Tables__Recieve_Payment() {
        initComponents();
         Connection myconnection;
            try
            {
            myconnection=DriverManager.getConnection(PATH+PLACE,USERNAME,PASSWORD);
            try
            {
            String a="select * from ordertable where paid='NO'";
            PreparedStatement mystatement=myconnection.prepareStatement(a); 
            ResultSet myresult=mystatement.executeQuery();
            DefaultTableModel mymodel=(DefaultTableModel)bill.getModel();

            String bno,name,tableno,totalbill;
            if(myresult.next())
            {
            do
            {
            bno=myresult.getString("billnumber");
            name=myresult.getString("name");
            tableno=myresult.getString("tablenumber");
            totalbill=myresult.getString("netbill");

            mymodel.addRow(new Object[]{bno,name,tableno,totalbill});
            }
            while(myresult.next());
            }
            }
            catch(Exception e)
            {
            JOptionPane.showMessageDialog(rootPane, "Error in query " + e.getMessage());
            e.printStackTrace();
            }
            finally
            {
            myconnection.close();
            }

            }
            catch(Exception e)
            {
            JOptionPane.showMessageDialog(rootPane, "Error in Connection " + e.getMessage());
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bill = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("0");

        bill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bill Number", "Name", "Table Number", "Total Bill"
            }
        ));
        bill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                billMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(bill);
        if (bill.getColumnModel().getColumnCount() > 0) {
            bill.getColumnModel().getColumn(0).setPreferredWidth(20);
            bill.getColumnModel().getColumn(1).setPreferredWidth(50);
            bill.getColumnModel().getColumn(2).setPreferredWidth(40);
            bill.getColumnModel().getColumn(3).setPreferredWidth(30);
        }

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Vacate Tables and Recieve Payment");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Current Booking List :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void billMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billMouseClicked
        int r=bill.getSelectedRow();
        a=Integer.valueOf((String)bill.getValueAt(r, 0));
    }//GEN-LAST:event_billMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Bill_Print obj=new Bill_Print(a);
        Parent_For_Admin.mydesktoppane.add(obj);
        obj.setVisible(true);
        this.revalidate();
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable bill;
    public static javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
